steps:
  - name: gradle:5.6.2-jdk8
    entrypoint: gradle
    args: ["clean"]
    dir: gradle-example
  - name: gradle:5.6.2-jdk8
    entrypoint: gradle
    args: ["build"]
    dir: gradle-example  
  - name: gradle:5.6.2-jdk8
    entrypoint: gradle
    args: ["publish"]
    dir: gradle-example  
